---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: eks-charts
  namespace: kube-system
spec:
  url: https://aws.github.io/eks-charts
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
spec:
  interval: 1h
  timeout: 5m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  chart:
    spec:
      chart: aws-load-balancer-controller
      version: "1.8.*"
      sourceRef:
        kind: HelmRepository
        name: eks-charts
  releaseName: aws-load-balancer-controller
  targetNamespace: system-tools
  values:
    replicaCount: 1
    autoScaling:
      enabled: true
      minReplicas: 1
    configureDefaultAffinity: false
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 100m
        memory: 256Mi
    podLabels:
      eks-addon-name: aws-load-balancer-controller
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
        matchLabels:
          eks-addon-name: aws-load-balancer-controller
    enableCertManager: false
    clusterName: lucas
    serviceAccount:
      create: true
      name: aws-load-balancer-controller
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::873841524148:role/load-balancer-controller