# apiVersion: source.toolkit.fluxcd.io/v1beta2
# kind: GitRepository
# metadata:
#   name: kong-charts
#   namespace: kube-system
# spec:
#   interval: 8640h
#   ref:
#     tag: kong-2.42.0
#   url: https://github.com/Kong/charts
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: aws-load-balancer-controller-crds
#   namespace: kube-system
# spec:
#   interval: 8640h
#   path: charts/kong/crds
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: kong-charts
