---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 24h
  url: https://kyverno.github.io/kyverno/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 1h
  timeout: 5m
  install:
    remediation:
      retries: 5
  chart:
    spec:
      chart: kyverno
      version: ">=3.2"
      sourceRef:
        kind: HelmRepository
        name: kyverno
  releaseName: kyverno
  targetNamespace: kyverno
  values:
    crds:
      groups:
        migration:
          enabled: false
  valuesFrom: []