---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  url: https://kubernetes-sigs.github.io/metrics-server/
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 1h
  timeout: 5m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  chart:
    spec:
      chart: metrics-server
      version: 3.12.*
      sourceRef:
        kind: HelmRepository
        name: metrics-server
  releaseName: metrics-server
  targetNamespace: system-tools
  values:
    replicas: 1
    podLabels:
      eks-addon-name: metrics-server
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
    args:
      - --kubelet-insecure-tls=true
      - --kubelet-preferred-address-types=InternalIP,Hostname,InternalDNS,ExternalDNS,ExternalIP
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 256Mi
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
        matchLabels:
          eks-addon-name: metrics-server