apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: flagger
  namespace: flux-system
spec:
  interval: 24h
  url: https://flagger.app
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger
  namespace: flux-system
spec:
  interval: 1h
  timeout: 5m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: flagger
      version: 1.x # update Flagger to the latest minor version
      interval: 6h # scan for new versions every six hours
      sourceRef:
        kind: HelmRepository
        name: flagger
  releaseName: flagger
  targetNamespace: flagger-system
  values:
    meshProvider: gatewayapi:v1beta1
    selectorLabels: service,app,name,app.kubernetes.io/name
    metricsServer: http://prometheus.linkerd-viz:9090
    linkerdAuthPolicy:
      create: true