apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: linkerd-smi
  namespace: flux-system
spec:
  interval: 24h
  url: https://linkerd.github.io/linkerd-smi
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-smi
  namespace: flux-system
spec:
  dependsOn:
    - name: linkerd-control-plane
  interval: 1h
  timeout: 5m
  chart:
    spec:
      chart: linkerd-smi
      version: 1.0.*
      sourceRef:
        kind: HelmRepository
        name: linkerd-smi
  releaseName: linkerd-smi
  targetNamespace: linkerd-smi
