apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bootstrap-namespaces
  namespace: flux-system
spec:
  interval: 1m0s
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: eks-flux-bootstrap
  path: namespaces
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bootstrap-configs-external-crds
  namespace: flux-system
spec:
  interval: 1m0s
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: eks-flux-bootstrap
  path: configs/external-crds  
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bootstrap-addons-common
  namespace: flux-system
spec:
  interval: 1m0s
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: eks-flux-bootstrap
  path: addons/common
  dependsOn:
    - name: bootstrap-namespaces
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bootstrap-configs-common
  namespace: flux-system
spec:
  interval: 1m0s
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: eks-flux-bootstrap
  path: configs/common
  dependsOn:
    - name: bootstrap-addons-common
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bootstrap-addons-ecosystem
  namespace: flux-system
spec:
  interval: 1m0s
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: eks-flux-bootstrap
  path: addons/ecosystem
  dependsOn:
    - name: bootstrap-configs-common