apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bootstrap-namespaces
  namespace: flux-system
spec:
  interval: 1m0s
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: eks-flux-bootstrap
  path: namespaces
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bootstrap-extends
  namespace: flux-system
spec:
  interval: 1m0s
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: eks-flux-bootstrap
  path: extends
  dependsOn:
    - name: bootstrap-namespaces
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bootstrap-addons-aws
  namespace: flux-system
spec:
  interval: 1m0s
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: eks-flux-bootstrap
  path: addons/aws
  dependsOn:
    - name: bootstrap-namespaces
    - name: bootstrap-extends
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bootstrap-addons-common
  namespace: flux-system
spec:
  interval: 1m0s
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: eks-flux-bootstrap
  path: addons/common
  dependsOn:
    - name: bootstrap-addons-aws